### PR TITLE
refactor: 8. Importing using created index files [TECH-344] 

### PR DESCRIPTION
**Pull request by JoakimSM**
Part eight of [TECH-344](https://jira.dhis2.org/browse/TECH-344)

This basically uses the created index files for importing.

Should resolve:
1. [#664(comment)](https://github.com/dhis2/capture-app/pull/664#discussion_r425883746)
2. [#664(comment)](https://github.com/dhis2/capture-app/pull/664#discussion_r425888854)

### CODE REVIEW

**Comment by JoakimSM** [comment]
Thanks for the feedback @paschalidi.

I was about to do the same for the other files in the loading masks folder, but I saw so many problems and I want to postpone it for another issue (some I didn't want keep, others needed a huge refactor etc).

**Comment by paschalidi** [comment]
I am not suggesting to do the refactor now but only to export them from the index for now and keep the refactoring for later step?

Is that not sensible?

**Comment by JoakimSM** [comment]
Fair enough 🙂 I'll do it as long as you don't expect refactor of the exported files 😉

**Comment by paschalidi** [comment]
Thanks a lot 🙇 !

**Comment by JoakimSM** [comment]
Exporting all LoadingMasks from the index file and using them. Please have a look.

**Pull request merged**
