### PR TITLE
Age Field

### PR DESCRIPTION
**Pull request by adeelshahid**

### CODE REVIEW

**Comment by zepto5** [comment]
From the design docs:
skjermbilde 2018-08-09 kl 11 10 26

The age field is more like a "time since" or "date of birth" field. The value that should be persisted to the server needs to be a date. 
When giving the date field a value, the year/month/day fields should give the age according to the current date.  
Changing year/month/day should update the date field. 

To see how it works, you could test it in the old Event Capture app.

**Comment by adeelshahid** [comment]
@zepto5 for all the tasks I am getting on the capture App i didn't see any **design doc** except now at the very end. Anyhow you guys need to help me a little quicker otherwise these tasks are hanging in the PR mode forever.

**Comment by lukasewvd** [comment]
@adeelshahid The design docs are posted in the new-capture-app channel on Slack. The design doc for input fields was not posted before the 3rd of August.

**Comment by zepto5** [comment]
Also this should have been described in the jira issue, which it is not...
I agree, we should.  Also, please ask in the new-capture-app channel if something is unclear or description missing in jira etc.

**Pull request closed without merging**
