### PR TITLE
feat: [DHIS2-17878][DHIS2-17048] Add overflow menu with actions to stages&events

### PR DESCRIPTION
**Pull request by eirikhaugstulen**
Summary:
- Add an overflow button on the end of each row in the stages & events widget
- Add a `Delete`-action
- Add a `Skip`-action
- Add an `Unskip`-action

### CODE REVIEW

**Review by henrikmv — COMMENTED** [review]
Nice @eirikhaugstulen! I could not find anything important, but I am not in a position to approve, so I am leaving this review without approval for now. Please ask for another review from someone else as well.

**Comment by eirikhaugstulen** [comment]
Thanks for the review @simonadomnisoru! I implemented your changes and also added some more validation on whether the user has write access and so on.

**Comment by simonadomnisoru** [comment]
> Tests are on their way, but thought you could have a look at the code in the meantime 👍

@eirikhaugstulen, solid work, the code looks good now 👏 ! Once you add some cypress tests I'll approve

**Comment by eirikhaugstulen** [comment]
@simonadomnisoru tests should be working now 👍

**Review by simonadomnisoru — APPROVED** [review]

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.42,2.41.2,2.40.5,2.39.7 versions

**Pull request merged**
