### PR TITLE
[DHIS2-11795] - Hide Non-searchable filters when in ACCESSIBLE-mode

### PR DESCRIPTION
**Pull request by EirikHaugstulen**
https://jira.dhis2.org/browse/DHIS2-11795

Fix permission issue when using the ACCESSIBLE-mode in WorkingList-component.

### CODE REVIEW

**Review by simonadomnisoru — APPROVED** [review]
LGTM!

**Review by JoakimSM — COMMENTED** [review]
Good job @EirikHaugstulen. I know we talked about creating this `filterHidden` prop, but looking at the code: does this do the same job as `filterDisabled`? If so, maybe we remove `filterDisabled` and use `filterHidden` instead? `filterHidden` seems to be the better name for the functionality here.

**Comment by EirikHaugstulen** [comment]
Yep, seems reasonable @JoakimSM! 
Removed `filterDisabled` and changed the current implementations to `filterHidden` 👍

**Review by JoakimSM — APPROVED** [review]
👍

**Pull request merged**
