### PR TITLE
feat: [DHIS2-17171] preview images in versions prior to 41

### PR DESCRIPTION
**Pull request by simonadomnisoru**
[DHIS2-17171](https://dhis2.atlassian.net/browse/DHIS2-17171)

**Tech summary**
- preview images in versions prior to 41 in all 3 working lists, Profile widget, StagesAndEvents widget, and the search results card
- the request to `/fileResource` for DE or TEA of type IMAGE is no longer needed and was removed 

[DHIS2-17171]: https://dhis2.atlassian.net/browse/DHIS2-17171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by JoakimSM — COMMENTED** [review]
Just had a quick look, so might be mistaken, but I think we currently have to do the request for versions prior to 41 (as we are using the filename for those version)? I'm fine with implementing https://dhis2.atlassian.net/browse/DHIS2-17171 first though.

**Comment by simonadomnisoru** [comment]
> Just had a quick look, so might be mistaken, but I think we currently have to do the request for versions prior to 41 (as we are using the filename for those version)? I'm fine with implementing https://dhis2.atlassian.net/browse/DHIS2-17171 first though.

Hey @JoakimSM, 
I added the implementation of [DHIS2-17171](https://dhis2.atlassian.net/browse/DHIS2-17171) to this branch. With this change, the request to `/fileResource` is no longer needed for all versions. Can you have a look? 
Thanks!

**Review by JoakimSM — APPROVED** [review]
LGTM

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.40.5,2.39.7 versions

**Pull request merged**
