### PR TITLE
fix: [DHIS2-13347] uncheck "yes/only" checkboxes

### PR DESCRIPTION
**Pull request by simonadomnisoru**

### CODE REVIEW

**Review by jasminenguyennn — APPROVED** [review]

**Review by JoakimSM — COMMENTED** [review]
This will at least break some keyboard functionality (this component is used for various field types, option sets (when not displayed in a dropdown), trueOnly, trueFalse). Looking into the git history I see that @jasminenguyennn recently changed onClick to onChange for the input element in this commit: https://github.com/dhis2/capture-app/commit/efbf771aff11b1a7b6e6c9e32f39365a3ea09572. Was this intentional? Reverting back to onClick seems to fix the issue.

**Comment by simonadomnisoru** [comment]
> This will at least break some keyboard functionality (this component is used for various field types, option sets (when not displayed in a dropdown), trueOnly, trueFalse). Looking into the git history I see that @jasminenguyennn recently changed onClick to onChange for the input element in this commit: [efbf771](https://github.com/dhis2/capture-app/commit/efbf771aff11b1a7b6e6c9e32f39365a3ea09572). Was this intentional? Reverting back to onClick seems to fix the issue.

Hey @JoakimSM, 
I reverted the change done to the input element in [efbf771](https://github.com/dhis2/capture-app/commit/efbf771aff11b1a7b6e6c9e32f39365a3ea09572). The delete enrollment event functionality seems to work well and is not affected by this rollback. Let me know if it looks good for you @jasminenguyennn.
Thank you both!

**Comment by jasminenguyennn** [comment]
hey @JoakimSM and @simonadomnisoru, I change `onClick` to `onChange` to remove the error Failed prop type on SingleSelectBox, please let me know how we should proceed to fix it. 

Screenshot 2022-06-09 at 15 03 08

**Review by JoakimSM — APPROVED** [review]

**Review by jasminenguyennn — APPROVED** [review]

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.39 and 2.38.2 versions

**Pull request merged**
