### PR TITLE
docs: naming guidelines proposal

### PR DESCRIPTION
**Pull request by simonadomnisoru**
I did some research on the best and worst practices for naming in JS. I put together this naming guidelines proposal using the ones that are compatible with our own codebase. 

Once this PR is approved by the other FEs in the team, the PR is closed and the new guidelines will be added to the [Code Guidelines repository wiki](https://github.com/dhis2/capture-app/wiki/Code-Guidelines).

### CODE REVIEW

**Review by j-nguyenn — APPROVED** [review]
I think this is a good start 👍

**Review by JoakimSM — COMMENTED** [review]
Looks good @simonadomnisoru 👍 Added some discussion points for our meeting later.

**Review by JoakimSM — APPROVED** [review]
Thanks. Looks good 👍

**Comment by simonadomnisoru** [comment]
The guidelines were added to the [Code Guidelines repository wiki.](https://github.com/dhis2/capture-app/wiki/Code-Guidelines#naming-guideline)

**Pull request closed without merging**
