### PR TITLE
fix: [DHIS2-11514] use org unit code

### PR DESCRIPTION
**Pull request by simonadomnisoru**

### CODE REVIEW

**Comment by eirikhaugstulen** [comment]
Hey, @simonadomnisoru!

Was testing this PR and noticed that you checked if orgUnit.code was set before initializing the registration form. Had to try the expected behavior on Play as well, and it seems like the registration form does not load if a orgUnitCode is not present. These codes should be optional I think, although I think they are often used. Is there something I have missed, or should this be treated as a bug? 
Thanks!

**Comment by simonadomnisoru** [comment]
> Hey, @simonadomnisoru!
> 
> Was testing this PR and noticed that you checked if orgUnit.code was set before initializing the registration form. Had to try the expected behavior on Play as well, and it seems like the registration form does not load if a orgUnitCode is not present. These codes should be optional I think, although I think they are often used. Is there something I have missed, or should this be treated as a bug? Thanks!

Hey @eirikhaugstulen,

You are right the orgUnit code is optional. Right now, it can be used by the program rules or to generate unique data elements. It is up to admins to set it up correctly if they want to use it in these scenarios. I remove the check as you suggested.

Thank you! 😄

**Review by jasminenguyennn — APPROVED** [review]

**Review by JoakimSM — APPROVED** [review]
Seems good to me 👍

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.36.13 version

**Pull request merged**
