### PR TITLE
fix: [DHIS2-13189] fix user name in widget comment

### PR DESCRIPTION
**Pull request by jasminenguyennn**

### CODE REVIEW

**Review by eirikhaugstulen — APPROVED** [review]
LGTM!

**Comment by simonadomnisoru** [comment]
Hey, 

I am not able to see the comment author in the `Schedule` event tab. The comment in the `Report` tab works properly now but the issues still persist on the `Schedule` tab mentioned in the Jira ticket. Did understand and I test the fix correctly?

Screenshot 2022-07-01 at 10 53 46

Thank you!

**Review by simonadomnisoru — APPROVED** [review]
LGTM!

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.39 and 2.38.1 versions

**Pull request merged**
