### PR TITLE
fix: [DHIS2-13291] convert dates for auto generated events

### PR DESCRIPTION
**Pull request by simonadomnisoru**

### CODE REVIEW

**Comment by eirikhaugstulen** [comment]
Hey, @simonadomnisoru!

This looks fine to me, I just have a small question;
How is our stance on renaming `sanitizedIncidentDate` => `sanitizedOccurredAt`? I know that this is absolutely a nitPick, just want to know how strict we are with the new terminology introduced in the new endpoints 😊

Thanks!

**Comment by simonadomnisoru** [comment]
> Hey, @simonadomnisoru!
> 
> This looks fine to me, I just have a small question; How is our stance on renaming `sanitizedIncidentDate` => `sanitizedOccurredAt`? I know that this is absolutely a nitPick, just want to know how strict we are with the new terminology introduced in the new endpoints 😊
> 
> Thanks!

Hey @eirikhaugstulen,

In my opinion, we should be pretty strict with using the new endpoints terminology and apply it everytime we have the opportunity. I change the code with your suggestion to reflect this. 

Thanks!

**Review by eirikhaugstulen — APPROVED** [review]
Looks good!

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.39 and 2.38.2 versions

**Pull request merged**
