### PR TITLE
feat: DHIS2-9257 Too many results functionality

### PR DESCRIPTION
**Pull request by paschalidi**
Ticker for this is: https://jira.dhis2.org/browse/DHIS2-9257

@cooper-joe  perhaps you can also have a look

### CODE REVIEW

**Comment by cooper-joe** [comment]
I tried to test this, but I can't find a situation where the message shows up. Every search I make returns a valid number of results 😅. Do you know if there's a search to perform on debug/ca-test-2.36 that can trigger this?

**Comment by paschalidi** [comment]
@cooper-joe ah yes sorry I forgot to explain. To get the error message simply type `,,,,` for the too many results I will create a user and update you

**Comment by paschalidi** [comment]
@cooper-joe use user `tracker`. Ask me if you dont know the password of this user. Also you will be able to see this only on the `MNCH / PNC (Adult Woman)`
image

**Comment by cooper-joe** [comment]
Thanks @paschalidi - looks good to me!

**Comment by paschalidi** [comment]
@cooper-joe thanks for taking a look!

**Review by JoakimSM — APPROVED** [review]
LGTM 👍

**Pull request merged**
