### PR TITLE
fix: [DHIS2-16010] app crashes on invalid programid

### PR DESCRIPTION
**Pull request by alaa-yahia**
Implements [DHIS2-16010](https://dhis2.atlassian.net/browse/DHIS2-16010)

- Ensure the context selector is consistently available on all pages when `programId` || `orgUnitId` is invalid.
- Update `withErrorMessageHandler` to use DHIS2 UI `NoticeBox` of type `error`

**Enrollment Page**
- Keep context selector always present
- Display NoticeBox if there is invalid  programmed || enrollementId || teiId

**EnrollmentEventNew Page**
- Redirect to enrollment page when there is invalid programId 

**Main Page:**
- Display Notice box if there is invalid orgUnitId || programId

**New Page**
- Ensure context selector is always present when there isn’t a valid programId || orgUnitId
- Display Notice box if there is invalid orgUnitId || programId

[DHIS2-16010]: https://dhis2.atlassian.net/browse/DHIS2-16010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by simonadomnisoru — COMMENTED** [review]
Hi @alaa-yahia,
Along with this fix, let's enable the [related disabled cypress](https://github.com/dhis2/capture-app/blob/master/cypress/e2e/ScopeSelector/ScopeSelector.feature#L31) scenario. It would also be nice if you could add one more scenario for the enrollment page. 
Thank you!

**Review by eirikhaugstulen — COMMENTED** [review]
Hey @alaa-yahia!
If you try to change to an invalid enrollmentId or teiId with this change, it seems like it's stuck in a loading state? Could you have a look at this? 😊

Before:
image

After:
image

**Review by simonadomnisoru — APPROVED** [review]
Looks great! 🎉

**Comment by alaa-yahia** [comment]
> Hey @alaa-yahia! If you try to change to an invalid enrollmentId or teiId with this change, it seems like it's stuck in a loading state? Could you have a look at this? 😊 I also struggle a bit when using enrollmentId=AUTO after this change, but it seems a bit more sporadic.
> 
> Before: image
> 
> After: image

Hey @eirikhaugstulen I have updated the code.

**Review by simonadomnisoru — APPROVED** [review]

**Comment by simonadomnisoru** [comment]
> Hey @alaa-yahia! If you try to change to an invalid enrollmentId or teiId with this change, it seems like it's stuck in a loading state? Could you have a look at this? 😊 I also struggle a bit when using enrollmentId=AUTO after this change, but it seems a bit more sporadic.

Hi @eirikhaugstulen, 
Can you please re-check if the latest commits fixed these issues you reported? For me, everything seems fine now.
Thank you! 🙏

**Review by eirikhaugstulen — APPROVED** [review]
Hey @alaa-yahia - so sorry for taking such a long time before getting back to you. It must have gone over my head. Feel free to ping me directly if you're blocked in the future. This looks good now 🎉

**Comment by alaa-yahia** [comment]
> Hey @alaa-yahia - so sorry for taking such a long time before getting back to you. It must have gone over my head. Feel free to ping me directly if you're blocked in the future. This looks good now 🎉

I forgot all about it either @eirikhaugstulen, otherwise I would have pinged you! No worries at all about the delay. Thank you for the review.

**Review by geethaalwan — APPROVED** [review]
Tested successfully on 2.42,2.41.2,2.40.6,2.39.8  versions

**Pull request merged**
